FROM node:10-alpine as builder

COPY package-lock.json ./
COPY angular.json ./
COPY package.json ./
COPY tsconfig.json ./
COPY tslint.json ./

RUN npm ci && mkdir /ng-app && mv ./node_modules ./ng-app

WORKDIR /ng-app

COPY . .

EXPOSE 4200

RUN npm run ng build --prod --output-path=dist