FROM node:10

RUN mkdir -p /app

WORKDIR /app

EXPOSE 4200/tcp

COPY package.json /app/
COPY angular.json /app/
COPY tsconfig.json /app/
COPY tslint.json /app/

#RUN ["npm", "install"]
RUN npm install
RUN npm run build

VOLUME /app/dist
