version: '3'
services:
  apache:
    image: webdevops/apache-dev:latest
    depends_on:
      - php
      - frontend
    volumes:
      - ./:/app/
      - ./:/docker/
    ports:
      - 800:80
      - 443:443
    links:
      - php
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_PHP_SOCKET=php:9000

  php:
    image: paula/php
    build:
      context: docker/php/
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    depends_on:
      - mongo
    links:
      - mongo
    working_dir: /app/
    volumes:
      - ./:/app/
      - ./:/docker/

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFexitIG_MONGODB_ADMINPASSWORD: root

  frontend:
    image: paula/frontend-builder
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
      - dist:/app/dist
    ports:
      - "4200:4200"

volumes:
  dist:
  mongo-db:
