imports:
    - { resource: repositories.yaml }
    - { resource: website_endpoints.yaml }
    - { resource: exporters.yaml }
    - { resource: importers.yaml }
    - { resource: manipulators.yaml }

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Repository,Exporter,Manipulator,Importer,Document,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Command\:
        resource: '../src/Command'
        tags: ['console.command']

    App\Service\ManipulatorContainer:
        arguments: ['collection']

    doctrine_mongo_db_param_converter:
        class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
        tags:
            - { name: request.param_converter, converter: doctrine.odm }
        arguments: ['@doctrine_mongodb']
